include: package:lint/analysis_options.yaml
analyzer:
  errors:
    missing_return : error
    must_be_immutable : ignore
    must_call_super : ignore
    invalid_use_of_protected_member : error
    parameter_assignments : error
    sort_unnamed_constructors_first : ignore
    sort_pub_dependencies : ignore

